// app-angular/src/app/sort-starter/sort-starter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sort-starter',
  templateUrl: './sort-starter.component.html',
  styleUrls: ['./sort-starter.component.scss']
})
export class SortStarterComponent implements OnInit {

  scrollingDown(){
    window.scrollTo({
      top: document.body.scrollHeight,
      behavior: 'smooth'
    })
  }
  constructor() { }

  ngOnInit(): void {
  }

}

<button (click)="scrollingDown()">Sort the deck</button>

// app-react/src/components/SortStarter/SortStarter.jsx
import React from 'react'
import s from './SortStarter.module.css'

let SortStarter = () => {

    return <div className={s.SortStarter}>
        <button onClick={() => {
            window.scrollTo({
                top: document.body.scrollHeight,
                behavior: 'smooth'
            })
        }}>Sort the deck
        </button>
    </div>
}

export default SortStarter
