// app-react/src/components/DeckSorterPage/ControlPanel/DeckCreater/DeckCreater.jsx
import React from 'react'
import s from './DeckCreater.module.css'

let DeckCreater = () => {
    return <div className={s.DeckCreater}>
        <div className={s.Title}>
            <b>CREATE DECK</b>
        </div>

        <div className={s.Selector}>
            deck name: <input type={'text'}/>
            cards in deck: <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
        </div>

        <div>
            <button>Create</button>
        </div>
    </div>

}

export default DeckCreater

// app-angular/src/app/deck-sorter-page/control-panel/deck-creater/deck-creater.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-deck-creater',
  templateUrl: './deck-creater.component.html',
  styleUrls: ['./deck-creater.component.scss']
})
export class DeckCreaterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class='Title'>
  <b>CREATE DECK</b>
</div>

<div class='Selector'>
  deck name: <input type='text'/>
  cards in deck: <select>
  <option>1</option>
  <option>2</option>
  <option>3</option>
</select>
</div>

<div>
  <button>Create</button>
</div>
