// app-react/src/DeckSorterPage/ControlPanel/DeckRemover/DeckRemover.jsx
import React from 'react'
import s from './DeckRemover.module.css'

let DeckRemover = () => {
    return <div className={s.DeckRemover}>
        <div className={s.Title}>
            <b>REMOVE DECK</b>
        </div>

        <div className={s.Selector}>
            deck name: <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
        </div>

        <div>
            <button>Remove</button>
        </div>
    </div>

}

export default DeckRemover

// app-angular/src/app/deck-sorter-page/control-panel/deck-remover/deck-remover.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-deck-remover',
  templateUrl: './deck-remover.component.html',
  styleUrls: ['./deck-remover.component.scss']
})
export class DeckRemoverComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class='Title'>
  <b>REMOVE DECK</b>
</div>

<div class='Selector'>
  deck name: <select>
  <option>1</option>
  <option>2</option>
  <option>3</option>
</select>
</div>

<div>
  <button>Remove</button>
</div>
