// app-vue/src/components/Informer/InfoAPP/InfoAPP.vue
<template>
    <div>
        <div>APP</div>
        <div class="APPtext">spa app developed on javascript
            <ul>libraries:
                <li>vue - work with DOM</li>
                <li>- - business layer</li>
                <li>- - work with state</li>
                <li>Vue Router - work with routing</li>
                <li>- - work with api requests</li>
            </ul>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'InfoAPP'
    }
</script>

<style scoped>
    .APPtext {
        font-style: normal;
        text-align: left;
        font-size: 22px;
        padding-left: 250px;
        padding-right: 1100px;
        letter-spacing: normal;
    }
</style>

// app-react/src/components/Informer/InfoAPP/InfoAPP.jsx
import React from 'react'
import s from '../Informer.module.css'

let InfoAPP = () => {
    return <div>
        <div>APP</div>
        <div className={s.APPtext}>spa app developed on javascript
            <ul>libraries:
                <li>react - work with DOM</li>
                <li>redux - business layer</li>
                <li>react-redux - work with state</li>
                <li>react-router-dom - work with routing</li>
                <li>thunk - work with api requests</li>
            </ul>
        </div>
    </div>
}

export default InfoAPP
