// app-react/src/DeckSorterPage/ControlPanel/DeckSorter/DeckSorter.jsx
import React from 'react'
import s from './DeckSorter.module.css'

let DeckSorter = () => {
    return <div className={s.DeckSorter}>
        <div className={s.Title}>
            <b>SHUFFLE DECK</b>
        </div>

        <div className={s.Selector}>
            deck name: <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
        </div>

        <div>
            <button>Shuffle</button>
        </div>
    </div>

}

export default DeckSorter

// app-angular/src/app/deck-sorter-page/control-panel/deck-sorter/deck-sorter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-deck-sorter',
  templateUrl: './deck-sorter.component.html',
  styleUrls: ['./deck-sorter.component.scss']
})
export class DeckSorterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class='Title'>
  <b>SHUFFLE DECK</b>
</div>

<div class='Selector'>
  deck name: <select>
  <option>1</option>
  <option>2</option>
  <option>3</option>
</select>
</div>

<div>
  <button>Shuffle</button>
</div>
