// app-react/src/components/DeckSorterPage/ControlPanel/DeckGetter/DeckGetter.jsx
import React from 'react'
import s from './DeckGetter.module.css'

let DeckGetter = () => {
    return <div className={s.DeckGetter}>
        <div className={s.Title}>
            <b>GET DECK</b>
        </div>

        <div className={s.Selector}>
            deck name: <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
        </div>

        <div>
            <button>Show</button>
        </div>
    </div>

}

export default DeckGetter

// app-angular/src/app/deck-sorter-page/control-panel/deck-getter/deck-getter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-deck-getter',
  templateUrl: './deck-getter.component.html',
  styleUrls: ['./deck-getter.component.scss']
})
export class DeckGetterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class='Title'>
  <b>GET DECK</b>
</div>

<div class='Selector'>
  deck name: <select>
  <option>1</option>
  <option>2</option>
  <option>3</option>
</select>
</div>

<div>
  <button>Show</button>
</div>
