// app-vue/src/components/DeckSorterPage/DeckSorterPage.vue
<template>
    <div class="DeckSorter">
        <Deck/>
        <ControlPanel/>
    </div>
</template>

<script>
    import ControlPanel from './ControlPanel/ControlPanel'
    import Deck from './Deck/Deck'

    export default {
        name: 'DeckSorterPage',
        components: {
            ControlPanel,
            Deck
        }
    }
</script>

<style scoped>
    .DeckSorter {
        grid-area: dsp;
        display: grid;
        grid-template-areas: 'd' 'cp';
        grid-template-rows: 75vh 25vh;
        grid-template-columns: 1fr;
    }
</style>

// app-react/src/DeckSorterPage/DeckSorterPage.jsx
import React from 'react'
import s from './DeckSorterPage.module.css'
import ControlPanel from './ControlPanel/ControlPanel'

let DeckSorterPage = () => {
    return <div className={s.DeckSorter}>
        <div className={s.Deck}>Deck</div>
        <ControlPanel/>
    </div>
}

export default DeckSorterPage
