// app-react/src/components/Informer/InfoAPI/InfoAPI.jsx
import React from 'react'
import s from '../Informer.module.css'

let InfoAPI = () => {
    return <div>
        <div>API</div>
        <div className={s.APItext}>api developed on .net c#
            <ul>requests:
                <li>get - api/values (получить список названий колод)</li>
                <li>get - api/values/getdeck (получить колоду по имени)</li>
                <li>post - api/values (создать именованную колоду карт)</li>
                <li>put - api/values/filldeckname (перетасовать колоду по имени)</li>
                <li>delete - api/values/deletedeckname (удалить колоду карт по имени)</li>
            </ul>
        </div>
    </div>
}

export default InfoAPI

// app-angular/src/app/informer/info-api/info-api.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-info-api',
  templateUrl: './info-api.component.html',
  styleUrls: ['./info-api.component.scss']
})
export class InfoApiComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="api">
  <div>API</div>
  <div>api developed on .net c#
    <ul>requests:
      <li>get - api/values (получить список названий колод)</li>
      <li>get - api/values/getdeck (получить колоду по имени)</li>
      <li>post - api/values (создать именованную колоду карт)</li>
      <li>put - api/values/filldeckname (перетасовать колоду по имени)</li>
      <li>delete - api/values/deletedeckname (удалить колоду карт по имени)</li>
    </ul>
  </div>
</div>
